# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cobweb\SvconnectorSuccessfactors\:
    resource: '../Classes/*'

  Cobweb\SvconnectorSuccessfactors\Service\ConnectorJson:
    public: true
    arguments:
      - !tagged_iterator connector.service
